In [50]:
import pandas as pd
import numpy as np

In [51]:
df = pd.read_csv('LoanExport.csv', low_memory=False)

In [52]:
col_name =df.columns[0]
df=df.rename(columns = {col_name:'CS'})
df.info()
df.shape

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 291451 entries, 0 to 291450
Data columns (total 28 columns):
 #   Column              Non-Null Count   Dtype  
---  ------              --------------   -----  
 0   CS                  291451 non-null  int64  
 1   FirstPaymentDate    291451 non-null  int64  
 2   FirstTimeHomebuyer  291451 non-null  object 
 3   MaturityDate        291451 non-null  int64  
 4   MSA                 291451 non-null  object 
 5   MIP                 291451 non-null  int64  
 6   Units               291451 non-null  int64  
 7   Occupancy           291451 non-null  object 
 8   OCLTV               291451 non-null  int64  
 9   DTI                 291451 non-null  int64  
 10  OrigUPB             291451 non-null  int64  
 11  LTV                 291451 non-null  int64  
 12  OrigInterestRate    291451 non-null  float64
 13  Channel             291451 non-null  object 
 14  PPM                 291451 non-null  object 
 15  ProductType         291451 non-nul

(291451, 28)

In [54]:
for col in ['FirstPaymentDate','MSA',
            'Occupancy','Channel','ProductType',
            'SellerName','PostalCode','ServicerName',
            'PropertyState','PPM','PropertyType','LoanPurpose',
            'NumBorrowers']:
    if col in df:
        del df[col]

In [55]:
df.dropna(inplace=True)
df.info()
df.shape

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 291451 entries, 0 to 291450
Data columns (total 15 columns):
 #   Column              Non-Null Count   Dtype  
---  ------              --------------   -----  
 0   CS                  291451 non-null  int64  
 1   FirstTimeHomebuyer  291451 non-null  object 
 2   MaturityDate        291451 non-null  int64  
 3   MIP                 291451 non-null  int64  
 4   Units               291451 non-null  int64  
 5   OCLTV               291451 non-null  int64  
 6   DTI                 291451 non-null  int64  
 7   OrigUPB             291451 non-null  int64  
 8   LTV                 291451 non-null  int64  
 9   OrigInterestRate    291451 non-null  float64
 10  LoanSeqNum          291451 non-null  object 
 11  OrigLoanTerm        291451 non-null  int64  
 12  EverDelinquent      291451 non-null  int64  
 13  MonthsDelinquent    291451 non-null  int64  
 14  MonthsInRepayment   291451 non-null  int64  
dtypes: float64(1), int64(12), object(2

(291451, 15)

In [56]:
df.CS.unique()

array([  0, 335, 342, 363, 366, 370, 375, 391, 396, 445, 462, 466, 471,
       476, 477, 478, 479, 481, 482, 483, 485, 486, 487, 489, 490, 491,
       492, 493, 494, 495, 496, 497, 498, 499, 500, 501, 502, 503, 504,
       505, 506, 507, 508, 509, 510, 511, 512, 513, 514, 515, 516, 517,
       518, 519, 520, 521, 522, 523, 524, 525, 526, 527, 528, 529, 530,
       531, 532, 533, 534, 535, 536, 537, 538, 539, 540, 541, 542, 543,
       544, 545, 546, 547, 548, 549, 550, 551, 552, 553, 554, 555, 556,
       557, 558, 559, 560, 561, 562, 563, 564, 565, 566, 567, 568, 569,
       570, 571, 572, 573, 574, 575, 576, 577, 578, 579, 580, 581, 582,
       583, 584, 585, 586, 587, 588, 589, 590, 591, 592, 593, 594, 595,
       596, 597, 598, 599, 600, 601, 602, 603, 604, 605, 606, 607, 608,
       609, 610, 611, 612, 613, 614, 615, 616, 617, 618, 619, 620, 621,
       622, 623, 624, 625, 626, 627, 628, 629, 630, 631, 632, 633, 634,
       635, 636, 637, 638, 639, 640, 641, 642, 643, 644, 645, 64

In [57]:
df['CS'] = np.where(df['CS'] == 0, 850, df['CS'])
df.CS.unique()

array([850, 335, 342, 363, 366, 370, 375, 391, 396, 445, 462, 466, 471,
       476, 477, 478, 479, 481, 482, 483, 485, 486, 487, 489, 490, 491,
       492, 493, 494, 495, 496, 497, 498, 499, 500, 501, 502, 503, 504,
       505, 506, 507, 508, 509, 510, 511, 512, 513, 514, 515, 516, 517,
       518, 519, 520, 521, 522, 523, 524, 525, 526, 527, 528, 529, 530,
       531, 532, 533, 534, 535, 536, 537, 538, 539, 540, 541, 542, 543,
       544, 545, 546, 547, 548, 549, 550, 551, 552, 553, 554, 555, 556,
       557, 558, 559, 560, 561, 562, 563, 564, 565, 566, 567, 568, 569,
       570, 571, 572, 573, 574, 575, 576, 577, 578, 579, 580, 581, 582,
       583, 584, 585, 586, 587, 588, 589, 590, 591, 592, 593, 594, 595,
       596, 597, 598, 599, 600, 601, 602, 603, 604, 605, 606, 607, 608,
       609, 610, 611, 612, 613, 614, 615, 616, 617, 618, 619, 620, 621,
       622, 623, 624, 625, 626, 627, 628, 629, 630, 631, 632, 633, 634,
       635, 636, 637, 638, 639, 640, 641, 642, 643, 644, 645, 64

In [58]:
df.FirstTimeHomebuyer.unique()

array(['N', 'X', 'Y'], dtype=object)

In [59]:
df = df[df.FirstTimeHomebuyer != 'X']
df.FirstTimeHomebuyer.unique()

array(['N', 'Y'], dtype=object)

In [60]:
df['FirstTimeHomebuyer'].value_counts()

FirstTimeHomebuyer
N    184154
Y     29282
Name: count, dtype: int64

In [61]:
df = df.rename(columns = {'FirstTimeHomebuyer':'IsFirstTime'})
df['IsFirstTime'] = np.where(df['IsFirstTime'] == 'Y', 1, 0)
df['IsFirstTime'].value_counts()

IsFirstTime
0    184154
1     29282
Name: count, dtype: int64

In [62]:
df.MaturityDate.unique()

array([202901, 202710, 202902, 202409, 202702, 202903, 202602, 202607,
       202904, 202905, 202906, 202907, 202908, 202909, 202910, 202911,
       202912, 203003, 203004, 203008, 202803, 203006, 203002, 202509,
       202611, 202703, 202706, 202502, 202612, 202705, 203001, 202704,
       202610, 202701, 202601, 202712, 202609, 202709, 202806, 202802,
       202605, 202811, 202608, 203101, 202805, 203012, 202809, 202804,
       202504, 203005, 202405, 202810, 203308, 202808, 202406, 202708,
       203007, 202812, 202606, 202807, 203009, 202506, 202707, 202711,
       203010, 202603, 202503, 203211, 203111, 202512, 202402, 202511,
       202510, 202604, 202410, 202508, 202801, 203312, 202507, 202408,
       203104, 204111, 204302, 202501, 203212, 203011, 202411, 202403,
       203304, 202404, 203106, 203210, 203202, 202505], dtype=int64)

In [63]:
df.MIP.unique()

array([25,  0, 30, 12, 35, 29, 17, 18, 20, 22,  6, 14, 33, 16, 52, 36, 28,
       11, 45, 27, 10, 50, 47,  7, 24, 15, 37, 32, 26,  1, 13, 21, 23, 55,
        4], dtype=int64)

In [64]:
df.Units.unique()

array([1, 2, 3, 4, 0], dtype=int64)

In [65]:
df['Units'].value_counts()

Units
1    209501
2      3242
3       346
4       345
0         2
Name: count, dtype: int64

In [66]:
df = df[df.Units != 0] #As it is a null value, so we have to remove those rows.

In [67]:
df.OCLTV.unique()

array([ 89,  73,  75,  76,  78,  90,  95,  80,  77,  85,  93,  70,  74,
        79,  72,  62,  44,  32,  64,  91,  53,  69,  60,  54,  52,  84,
        68,  36,  55,  96,  97,  46,  58,  63,  83,  87,  94,  48,  50,
        51,  67,  86,  81,  66,  71,  82,  88,  26,  59,  57,  61,  30,
        24,  34,  37,  42,  65,  31, 100,   7,  38,  39,  16,  41,  33,
        92,  40,  35,  56,  22,  28,  43,  47,  49,  98,  29,  45,  25,
       103,  10,  18,  23,  20,  15, 102, 101,  14,  21,  27, 105,  19,
         8,   0, 104,  17, 110,  99,  12,   6,  13,   9,  11], dtype=int64)

In [68]:
df.DTI.unique()

array([27, 17, 16, 14, 18, 40, 21, 38, 19, 23, 45, 28, 29, 15, 43, 25, 24,
       26, 20, 35, 46, 39, 33, 48, 30, 31, 22, 56, 32, 12,  6, 37, 36, 42,
       34, 11, 41,  8, 44, 55,  0, 51, 10,  7, 47,  9, 13, 65, 54,  2, 53,
       57,  5,  3,  4, 50, 59, 49, 52, 64, 60, 58,  1, 61, 62, 63],
      dtype=int64)

In [69]:
df = df[df.DTI != 0]

In [70]:
df.OrigUPB.unique()

array([117000, 109000,  88000, 160000, 207000, 111000,  55000,  35000,
       126000, 200000,  70000,  93000,  79000,  54000,  80000, 231000,
       145000, 187000, 148000,  90000,  65000,  86000, 122000, 157000,
        94000,  63000,  50000, 100000, 191000, 204000, 222000, 189000,
        57000, 202000, 137000,  56000, 140000,  18000,  76000,  77000,
       151000, 118000, 182000,  98000,  89000, 172000,  82000, 240000,
       102000, 173000,  51000, 169000, 101000, 152000, 141000,  47000,
       128000, 133000, 135000, 115000, 144000, 146000, 212000, 176000,
       214000, 190000, 227000,  99000,  83000,  49000,  29000, 124000,
       132000, 150000, 300000,  95000, 149000, 162000, 226000, 110000,
       112000, 219000, 236000,  67000, 195000, 164000, 198000,  60000,
       194000, 147000, 104000,  72000, 183000, 154000, 179000,  66000,
       210000,  46000,  96000, 225000, 156000, 235000, 113000, 139000,
        74000,  68000,  69000, 238000, 142000,  73000,  48000,  97000,
      

In [71]:
df.LTV.unique()

array([ 89,  73,  75,  76,  78,  90,  95,  80,  77,  85,  93,  70,  74,
        79,  72,  62,  44,  32,  64,  91,  53,  69,  60,  54,  52,  84,
        68,  36,  55,  96,  97,  46,  58,  63,  83,  87,  94,  48,  50,
        51,  67,  86,  81,  66,  71,  82,  88,  26,  59,  57,  61,  30,
        24,  34,  37,  42,  65,  31,   7,  38,  39,  16,  41,  33,  92,
        40,  22,  28,  43,  47, 100,  49,  56,  98,  35,  45,  25,  10,
        18,  23,  20,  15,  29, 103,  14,  21,  27,  19,   8,  17,  12,
         6,  13,   9,  11,   0], dtype=int64)

In [72]:
df = df[df.LTV != 0]

In [73]:
df.OrigInterestRate.unique()

array([ 6.75 ,  6.5  ,  6.875,  7.125,  7.   ,  7.25 ,  6.625,  7.75 ,
        7.2  ,  7.5  ,  7.625,  7.875,  6.25 ,  8.125,  7.15 ,  7.375,
        6.375,  8.75 ,  7.1  ,  7.05 ,  6.95 ,  8.   ,  8.625,  8.375,
        8.5  ,  6.125,  6.   ,  8.25 ,  8.99 ,  5.625,  9.   ,  5.875,
        9.125,  6.99 ,  8.365,  8.875,  6.975,  7.3  ,  7.313,  9.625,
        9.25 ,  5.75 ,  7.85 ,  8.695,  7.775,  7.29 ,  7.405,  9.5  ,
        9.375,  9.75 ,  7.13 ,  5.99 ,  6.999,  7.055,  7.09 ,  6.785,
        7.08 ,  7.025,  7.7  ,  7.58 , 10.5  ,  7.55 ,  7.445,  9.875,
        6.85 ,  6.925,  6.9  ,  8.37 ,  5.375,  7.095,  7.19 ,  7.456,
        9.675,  7.475,  7.22 ,  7.17 ,  8.7  ,  7.301,  8.9  , 10.   ,
        6.62 ,  7.325, 10.375,  7.8  ,  7.4  , 10.85 ,  7.185,  7.245,
        5.25 , 11.5  ,  6.94 ,  6.87 ,  7.65 ,  7.312,  7.28 ,  7.39 ,
        7.07 ,  5.5  ,  7.43 ,  7.48 ,  6.88 ,  8.45 ,  6.895,  6.3  ,
        7.49 ,  6.8  ,  6.63 ,  8.05 ,  7.275,  7.175,  7.225,  7.075,
      

In [74]:
df.OrigLoanTerm.unique()

array([360, 345, 306, 335, 322, 327, 358, 355, 356, 354, 346, 344, 348,
       313, 316, 353, 319, 332, 336, 338, 312, 328, 351, 333, 359, 331,
       337, 334, 357, 330, 350, 341, 343, 325, 326, 324, 347, 352, 329,
       339, 317, 349, 342, 304, 340, 301, 309, 315, 323, 321, 320, 302,
       318, 303, 307, 305, 361, 314, 308, 310, 311], dtype=int64)

In [75]:
df.EverDelinquent.unique()

array([0, 1], dtype=int64)

In [76]:
df.MonthsDelinquent.unique()

array([  0, 104,   5,  23,  32,   1,   2,   4,  20,  10,   3,  34,  35,
         6,  11, 153,   7,   8,  18,  78,  24,  14,  17,  25,   9,  66,
        36,  19,  15,  27,  28,  49,  13,  50,  26,  29,  12,  16,  21,
        22, 118,  30,  69, 158,  62,  43,  38,  64,  71,  92,  41,  91,
        83, 130, 102,  33,  31,  85,  47,  45,  37,  61,  55,  48,  74,
        39, 151, 124, 105,  60,  84,  46,  51,  99, 107,  73, 170,  86,
       149,  40, 106,  63, 112, 110,  54,  77, 122, 180,  58,  53, 100,
       116,  56,  42, 163, 111, 141, 169,  59,  57,  44,  82,  70,  79,
        65, 134,  89, 150, 113, 109,  52, 146,  75,  81, 133,  97, 103,
        67, 101,  72, 120,  87,  93, 140,  96,  98, 132, 108, 115,  80,
       121, 127, 138,  88, 156, 119,  95, 129, 139, 165, 117,  90, 114,
       157,  68,  76, 160, 123, 148,  94, 143, 137, 152, 175, 131, 162,
       179, 145, 128, 126, 178, 172, 135, 125, 168, 159, 142, 161, 136,
       147, 144, 171, 154], dtype=int64)

In [77]:
df.MonthsInRepayment.unique()

array([ 52, 144,  67,  35,  54,  42,  44,  64, 212,  37,  47,  53,  55,
        66,  26,  38,  36,  39,  40,  11, 176,  46, 197, 210,  56, 118,
        63,  24,  28,  91,  50,  22, 211, 199,  23,  30, 125,  41,  76,
        49,  18,  19,  43,  60,  83,  95,  29,  45,  13,   6,  48,  62,
        14,  15, 111,  51,  17,  75,  58,  27,  10,  31, 133, 165, 156,
        33,  68, 205,  57, 159,  81, 194, 114,  59, 100, 134, 128,  71,
         7,  65,  74,  79, 174, 195, 151,  34, 149,  21,  12, 137, 130,
        69,  70, 173, 166,  61, 160,  20, 178,   3,  72, 147,   2,  32,
       164, 139, 148,  92, 209, 102,  87,  94,  73, 123,  16, 142, 108,
         1, 172, 109, 141, 175, 103, 168,   5, 155, 177, 158, 138,  25,
       110,  98,  84, 136,   8, 121, 179,   4, 154, 161, 157, 150,  80,
       170,  77,   9, 183,  93, 143, 162, 126,  89, 208, 184,  82, 145,
       117, 101, 122, 107, 193,  85,  78, 169, 104, 131, 140, 163, 112,
       206, 135, 132, 124, 186, 127, 189, 190, 198, 192, 167, 14

In [78]:
# Create new variable for Credit Range since that is commonly what is looked at in the industry.
# New values = Poor (0-650), Fair (650-700), Good (700-750), Excellent (750-900)
df['CreditRange'] = pd.cut(df.CS,[550,650,700,750,1e6],4,labels=['Poor','Fair','Good','Excellent'])
df.CreditRange.unique()

['Excellent', NaN, 'Poor', 'Fair', 'Good']
Categories (4, object): ['Poor' < 'Fair' < 'Good' < 'Excellent']

In [79]:
df.shape

(210862, 16)

In [80]:
df.isnull().sum()

CS                     0
IsFirstTime            0
MaturityDate           0
MIP                    0
Units                  0
OCLTV                  0
DTI                    0
OrigUPB                0
LTV                    0
OrigInterestRate       0
LoanSeqNum             0
OrigLoanTerm           0
EverDelinquent         0
MonthsDelinquent       0
MonthsInRepayment      0
CreditRange          506
dtype: int64

In [82]:
df.dropna(inplace=True)
df.shape

(210356, 16)

In [83]:
df['CreditRange'].value_counts()

CreditRange
Good         71842
Excellent    56288
Fair         54256
Poor         27970
Name: count, dtype: int64

In [84]:
# Create new variable for LTV Range
df['LTV_range'] = pd.cut(df.LTV,[0,25,50,1000],3,labels=['Low','Medium','High'])
df.LTV_range.unique()

['High', 'Medium', 'Low']
Categories (3, object): ['Low' < 'Medium' < 'High']

In [88]:
# Create new variable Repay range
df['Repay_range'] = pd.cut(df.MonthsInRepayment,[0,48,96,144,192,240],5,
                           labels=['Poor','Fair','Good', 'Very Good', 'Excellent'])

In [95]:
df['Repay_range'].value_counts()

Repay_range
Poor         107159
Fair          72838
Good          13694
Very Good      8581
Excellent      8084
Name: count, dtype: int64

In [97]:
df.shape
df.info()
df.isnull().values.any()

<class 'pandas.core.frame.DataFrame'>
Index: 210356 entries, 0 to 291450
Data columns (total 18 columns):
 #   Column             Non-Null Count   Dtype   
---  ------             --------------   -----   
 0   CS                 210356 non-null  int64   
 1   IsFirstTime        210356 non-null  int32   
 2   MaturityDate       210356 non-null  int64   
 3   MIP                210356 non-null  int64   
 4   Units              210356 non-null  int64   
 5   OCLTV              210356 non-null  int64   
 6   DTI                210356 non-null  int64   
 7   OrigUPB            210356 non-null  int64   
 8   LTV                210356 non-null  int64   
 9   OrigInterestRate   210356 non-null  float64 
 10  LoanSeqNum         210356 non-null  object  
 11  OrigLoanTerm       210356 non-null  int64   
 12  EverDelinquent     210356 non-null  int64   
 13  MonthsDelinquent   210356 non-null  int64   
 14  MonthsInRepayment  210356 non-null  int64   
 15  CreditRange        210356 non-null  cat

False

In [99]:
df_grouped = df.groupby(by=['CreditRange','IsFirstTime','LTV_range','Repay_range'], observed=True)
df_grouped.describe()

CS                         \
                                                count        mean        std   
CreditRange IsFirstTime LTV_range Repay_range                                  
Poor        0           Low       Poor           16.0  628.500000  20.053262   
                                  Fair           13.0  635.384615  13.859644   
                                  Good            3.0  637.333333   7.094599   
                                  Very Good       2.0  608.000000  35.355339   
                                  Excellent       1.0  631.000000        NaN   
...                                               ...         ...        ...   
Excellent   1           High      Poor         3033.0  772.002638  20.537789   
                                  Fair         2201.0  773.215811  21.250652   
                                  Good          474.0  775.510549  19.739233   
                                  Very Good     312.0  778.102564  20.924510   
                                  Excellent     241.0  784.340249  27.568105   

                                                                           \
                                                 min    25%    50%    75%   
CreditRange IsFirstTime LTV_range Repay_range                               
Poor        0           Low       Poor         574.0  617.0  632.0  645.5   
                                  Fair         599.0  630.0  633.0  647.0   
                                  Good         631.0  633.5  636.0  640.5   
                                  Very Good    583.0  595.5  608.0  620.5   
                                  Excellent    631.0  631.0  631.0  631.0   
...                                              ...    ...    ...    ...   
Excellent   1           High      Poor         751.0  758.0  767.0  779.0   
                                  Fair         751.0  759.0  768.0  780.0   
                                  Good         751.0  761.0  772.0  786.0   
                                  Very Good    751.0  764.0  774.0  787.0   
                                  Excellent    751.0  765.0  779.0  792.0   

                                                     MaturityDate  \
                                                 max        count   
CreditRange IsFirstTime LTV_range Repay_range                       
Poor        0           Low       Poor         650.0         16.0   
                                  Fair         650.0         13.0   
                                  Good         645.0          3.0   
                                  Very Good    633.0          2.0   
                                  Excellent    631.0          1.0   
...                                              ...          ...   
Excellent   1           High      Poor         850.0       3033.0   
                                  Fair         850.0       2201.0   
                                  Good         850.0        474.0   
                                  Very Good    850.0        312.0   
                                  Excellent    850.0        241.0   

                                                              ...  \
                                                        mean  ...   
CreditRange IsFirstTime LTV_range Repay_range                 ...   
Poor        0           Low       Poor         202903.187500  ...   
                                  Fair         202903.153846  ...   
                                  Good         202902.666667  ...   
                                  Very Good    202902.500000  ...   
                                  Excellent    202903.000000  ...   
...                                                      ...  ...   
Excellent   1           High      Poor         202903.363666  ...   
                                  Fair         202902.715129  ...   
                                  Good         202903.120253  ...   
                                  Very Good    202903.04

In [102]:
df.to_csv('LoanExport.csv', index=False)